;;; client-tests.el --- WhatsAppel client regression tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)

(defconst whatsapp-test--message
  '(("id" . "m1") ("from" . "551111@s.whatsapp.net") ("name" . "Ana")
    ("me" . nil) ("kind" . "text") ("text" . "Hello") ("ts" . 1700000000)))

(defmacro whatsapp-test--chat (&rest body)
  `(with-temp-buffer
     (whatsapp-chat-mode)
     (setq whatsapp-chat--jid "551111@s.whatsapp.net" whatsapp-chat--target "551111")
     (let ((whatsapp-auto-load-images nil)) ,@body)))

(ert-deftest whatsapp-json-false-is-not-an-outbound-message ()
  (with-temp-buffer
    (insert "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"me\":false,\"ok\":true}")
    (progn (setq-local url-http-response-status 200)
      (let ((result (whatsapp--response)))
        (should (= 200 (car result)))
        (should-not (cdr (assoc "me" (cdr result))))
        (should (eq t (cdr (assoc "ok" (cdr result)))))))))

(ert-deftest whatsapp-token-destination-restricted ()
  (let ((whatsapp-bridge-token "secret"))
    (dolist (url '("http://127.0.0.1:7337" "http://[::1]:7337" "https://bridge.example"))
      (let ((whatsapp-bridge-url url)) (should (null (whatsapp--validate-bridge)))))
    (dolist (url '("http://example.com" "file:///tmp/token" "https://user:pass@example.com"
                   "https://bridge.example/?token=foo" "https://bridge.example/#foo"))
      (let ((whatsapp-bridge-url url)) (should-error (whatsapp--validate-bridge) :type 'user-error))))
  (let ((whatsapp-bridge-token "token\r\nInjected: yes"))
    (should-error (whatsapp--validate-bridge) :type 'user-error)))

(ert-deftest whatsapp-original-file-preserves-bytes-and-name ()
  (let ((file (make-temp-file "whatsapp-original-" nil ".heic")) payload route)
    (unwind-protect
        (progn
          (let ((coding-system-for-write 'binary))
            (with-temp-file file (set-buffer-multibyte nil) (insert (unibyte-string 0 255 10 42))))
          (cl-letf (((symbol-function 'whatsapp--request)
                     (lambda (_method path body) (setq route path payload body) '(200))))
            (should (whatsapp--send-media-to "5511" 'image file)))
          (should (equal route "/send/document"))
          (should (equal (cdr (assoc "filename" payload)) (file-name-nondirectory file)))
          (should (equal (whatsapp--data-uri-bytes (cdr (assoc "data" payload)))
                         (unibyte-string 0 255 10 42))))
      (delete-file file))))

(ert-deftest whatsapp-media-compatibility-does-not-relabel-gif ()
  (should (eq 'document (whatsapp--safe-media-kind 'gif "image/gif")))
  (should (eq 'gif (whatsapp--safe-media-kind 'gif "video/mp4")))
  (should (eq 'document (whatsapp--safe-media-kind 'audio "audio/flac")))
  (should (eq 'image (whatsapp--safe-media-kind 'image "image/png")))
  (should (equal "application/zip" (whatsapp--guess-mime "archive.ZIP" 'document)))
  (should (equal "application/octet-stream" (whatsapp--guess-mime "unknown.thing" 'image))))

(ert-deftest whatsapp-oversized-attachment-rejected-before-read ()
  (let ((file (make-temp-file "whatsapp-limit-")) (whatsapp-max-file-bytes 3))
    (unwind-protect
        (progn (with-temp-file file (insert "1234"))
               (should-error (whatsapp--file->data-uri file "text/plain") :type 'user-error))
      (delete-file file))))

(ert-deftest whatsapp-cache-evicts-lru-and-is-chat-scoped ()
  (let ((whatsapp--media-cache (make-hash-table :test 'equal))
        (whatsapp--media-order nil) (whatsapp-media-cache-max-bytes 8))
    (whatsapp--cache-put 'a "aaaa") (whatsapp--cache-put 'b "bbbb")
    (whatsapp--cache-get 'a) (whatsapp--cache-put 'c "cccc")
    (should (gethash 'a whatsapp--media-cache))
    (should-not (gethash 'b whatsapp--media-cache))
    (whatsapp--cache-put 'huge "0123456789")
    (should-not (gethash 'huge whatsapp--media-cache))
    (let ((whatsapp-chat--jid "one"))
      (let ((key (whatsapp--media-key "same-id" "image")))
        (let ((whatsapp-chat--jid "two"))
          (should-not (equal key (whatsapp--media-key "same-id" "image"))))))))

(ert-deftest whatsapp-render-preserves-draft-and-cursor ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (insert "unsent text")
   (backward-char 4)
   (let ((offset (- (point) whatsapp-chat--input-marker)))
     (whatsapp-chat--render (list whatsapp-test--message
                                '(("id" . "m2") ("text" . "New message"))))
     (should (equal "unsent text" (whatsapp-chat--current-input)))
     (should (= offset (- (point) whatsapp-chat--input-marker)))
     (insert "!")
     (should (equal "unsent !text" (whatsapp-chat--current-input))))))

(ert-deftest whatsapp-render-preserves-history-position-and-org-message ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (goto-char (point-min)) (search-forward "Hello") (backward-char 2)
   (let ((saved (whatsapp-chat--position (point))))
     (whatsapp-chat--render (list '(("id" . "m0") ("text" . "Older")) whatsapp-test--message))
     (should (equal saved (whatsapp-chat--position (point))))
     (should (equal "m1" (cdr (assoc "id" (whatsapp--message-at-point)))))
     (should-error (insert "x") :type 'text-read-only))))

(ert-deftest whatsapp-refresh-coalesces-and-retains-history-on-error ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (let ((calls 0) callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_method _path _payload cb) (cl-incf calls) (setq callback cb))))
       (whatsapp-chat-refresh) (whatsapp-chat-refresh)
       (should (= calls 1)) (should whatsapp--refresh-pending)
       (funcall callback '(503 ("error" . "offline")))
       (should-not whatsapp--refresh-pending)
       (should (equal (list whatsapp-test--message) whatsapp-chat--messages))
       (should whatsapp--last-error)))))

(ert-deftest whatsapp-refresh-does-not-redraw-unchanged-history ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (let ((before (buffer-chars-modified-tick)))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _b callback)
                  (funcall callback (cons 200 (list (copy-tree whatsapp-test--message)))))))
       (whatsapp-chat-refresh))
     (should (= before (buffer-chars-modified-tick))))))

(ert-deftest whatsapp-refresh-after-send-queues-one-followup ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (let ((calls 0) callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_method _path _payload cb) (cl-incf calls) (setq callback cb))))
       (whatsapp-chat-refresh) (whatsapp-chat-refresh t) (whatsapp-chat-refresh t)
       (funcall callback (cons 200 (list whatsapp-test--message)))
       (should (= calls 2))
       (funcall callback (cons 200 (list whatsapp-test--message)))
       (should (= calls 2)) (should-not whatsapp--refresh-pending)))))

(ert-deftest whatsapp-async-completes-once-and-disables-redirects ()
  (let ((whatsapp-bridge-token "test") (calls 0) callback timeout request-buffer)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_url cb &rest _)
                 (should (= url-max-redirections 0))
                 (setq callback cb request-buffer (generate-new-buffer " *wa-response*"))))
              ((symbol-function 'run-at-time)
               (lambda (_seconds _repeat cb &rest _) (setq timeout cb) 'test-timer))
              ((symbol-function 'cancel-timer) #'ignore))
      (whatsapp--url-request-async "GET" "/chats" nil
                               (lambda (result) (cl-incf calls) (should (= 200 (car result)))))
      (with-current-buffer request-buffer
        (insert "HTTP/1.1 200 OK\r\n\r\n[]")
        (progn (setq-local url-http-response-status 200) (funcall callback nil)))
      (should-not (buffer-live-p request-buffer))
      (funcall timeout)
      (should (= calls 1)))))

(ert-deftest whatsapp-async-timeout-releases-buffer ()
  (let ((whatsapp-bridge-token "test") timeout request-buffer result)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (&rest _) (setq request-buffer (generate-new-buffer " *wa-timeout*"))))
              ((symbol-function 'run-at-time)
               (lambda (_seconds _repeat cb &rest _) (setq timeout cb) 'test-timer))
              ((symbol-function 'cancel-timer) #'ignore))
      (whatsapp--url-request-async "GET" "/chats" nil (lambda (r) (setq result r)))
      (funcall timeout)
      (should-not (car result))
      (should-not (buffer-live-p request-buffer)))))

(ert-deftest whatsapp-pq-key-path-rejects-traversal ()
  (should (string-suffix-p "5511@s.whatsapp.net.public"
                           (whatsapp-pq--contact-file "5511@s.whatsapp.net")))
  (dolist (jid '("../identity" "../../outside" "/absolute" "x/y" ""))
    (should-error (whatsapp-pq--contact-file jid) :type 'user-error)
    (should-error (whatsapp-pq--contact-fpr jid) :type 'user-error)))

(ert-deftest whatsapp-dashboard-filters-and-literal-search ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let ((chats '((("jid" . "1") ("name" . "Ana [work]") ("unread" . 2))
                   (("jid" . "2@g.us") ("name" . "Family") ("unread" . 0)))))
      (setq whatsapp-root--filter 'unread)
      (should (= 1 (length (cl-remove-if-not #'whatsapp-root--visible-p chats))))
      (setq whatsapp-root--filter 'groups)
      (should (equal "2@g.us" (cdr (assoc "jid" (car (cl-remove-if-not #'whatsapp-root--visible-p chats))))))
      (setq whatsapp-root--filter 'all whatsapp-root--query "[work]")
      (whatsapp-root--render chats)
      (should (string-match-p "Ana" (buffer-string)))
      (should-not (string-match-p "Family" (buffer-string)))
      (should (next-button (point-min))))))

(ert-deftest whatsapp-return-on-history-does-not-send-draft ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (insert "secret draft")
   (goto-char (point-min)) (search-forward "Hello")
   (let (menu)
     (cl-letf (((symbol-function 'whatsapp-chat-message-menu) (lambda () (setq menu t)))
               ((symbol-function 'whatsapp-chat-send-input) (lambda () (ert-fail "Unexpected send"))))
       (whatsapp-chat-return)
       (should menu)
       (should (equal "secret draft" (whatsapp-chat--current-input)))))))

(ert-deftest whatsapp-poll-refreshes-visible-history-only ()
  (let ((hidden (generate-new-buffer " *wa-hidden*"))
        (visible (generate-new-buffer " *wa-visible*")) (calls 0))
    (unwind-protect
        (progn
          (dolist (b (list hidden visible)) (with-current-buffer b (whatsapp-chat-mode)))
          ;; Discover visible windows directly; unrelated buffers are not scanned.
          (cl-letf (((symbol-function 'frame-list) (lambda () '(fixture-frame)))
                    ((symbol-function 'frame-visible-p) (lambda (_) t))
                    ((symbol-function 'window-list) (lambda (&rest _) '(fixture-window)))
                    ((symbol-function 'window-buffer) (lambda (_) visible))
                    ((symbol-function 'whatsapp-chat-refresh)
                     (lambda (&rest _)
                       (when (eq (current-buffer) visible) (cl-incf calls))
                       (when (eq (current-buffer) hidden) (setq calls -100)))))
            (whatsapp--poll)
            (should (= calls 1))))
      (kill-buffer hidden) (kill-buffer visible))))

(ert-deftest whatsapp-render-never-downloads-media-synchronously ()
  (whatsapp-test--chat
   (let ((whatsapp-auto-load-images t))
     (cl-letf (((symbol-function 'whatsapp--request)
                (lambda (&rest _) (ert-fail "Blocking media request during render")))
               ((symbol-function 'display-graphic-p) (lambda (&rest _) nil)))
       (whatsapp-chat--render
        '((("id" . "image1") ("kind" . "image") ("media" . (("Url" . "https://cdn.invalid"))))))))))

(ert-deftest whatsapp-root-navigation-skips-whole-cards-and-keeps-selection ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let ((chats '((("jid" . "1") ("name" . "Ana"))
                   (("jid" . "2") ("name" . "Bob")))))
      (whatsapp-root--render chats)
      (goto-char (point-min)) (whatsapp-root-next)
      (should (equal "1" (get-text-property (point) 'whatsapp-jid)))
      (whatsapp-root-next)
      (should (equal "2" (get-text-property (point) 'whatsapp-jid)))
      (whatsapp-root-prev)
      (should (equal "1" (get-text-property (point) 'whatsapp-jid)))
      (whatsapp-root-next)
      (let ((copy (copy-tree chats)))
        (setcdr (assoc "jid" (cadr copy)) (copy-sequence "2"))
        (whatsapp-root--render copy))
      (should (equal "2" (get-text-property (point) 'whatsapp-jid))))))

(ert-deftest whatsapp-lazy-media-concurrency-and-failure-backoff ()
  (whatsapp-test--chat
   (let ((whatsapp--media-cache (make-hash-table :test 'equal))
         (whatsapp--media-pending (make-hash-table :test 'equal))
         (whatsapp--media-queue nil) (whatsapp--media-active 0)
         (whatsapp--media-pump-timer nil) callbacks (calls 0))
     (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) (selected-window)))
              ((symbol-function 'run-at-time) (lambda (&rest _) 'test-timer))
               ((symbol-function 'whatsapp--request-async)
                (lambda (_method _path _payload callback)
                  (cl-incf calls) (setq callbacks (append callbacks (list callback))))))
       (dolist (id '("1" "2" "3")) (whatsapp--queue-image id "image" '(("Url" . "test"))))
       (whatsapp--media-pump)
       (should (= 2 calls)) (should (= 2 whatsapp--media-active))
       (funcall (pop callbacks) '(410 ("error" . "expired")))
       (should (= 3 calls)) (should (= 2 whatsapp--media-active))
       (whatsapp--queue-image "1" "image" '(("Url" . "test")))
       (should-not whatsapp--media-queue)
       (dolist (callback callbacks) (funcall callback '(410)))
       (should (= 0 whatsapp--media-active))))))

(ert-deftest whatsapp-invalid-json-response-is-not-empty-history ()
  (with-temp-buffer
    (setq-local url-http-response-status 200)
    (insert "HTTP/1.1 200 OK\r\n\r\n{broken json")
    (should (eq :invalid-json (cdr (whatsapp--response))))))

(ert-deftest whatsapp-history-is-protected-at-message-boundaries ()
  (whatsapp-test--chat
   (whatsapp-chat--render (list whatsapp-test--message))
   (goto-char (point-min))
   (should-error (insert "x") :type 'text-read-only)
   (goto-char whatsapp-chat--input-marker)
   (insert "editable")
   (should (equal "editable" (whatsapp-chat--current-input)))))

(ert-deftest whatsapp-unavailable-original-preview-has-no-path-injection ()
  (should (equal ".bin" (whatsapp--media-suffix "application/../../owned")))
  (should-not (whatsapp--image-type-from-mime "image/svg+xml")))
