;;; delivery-tests.el --- RC11 native regression cases -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)

(defun wa-delivery-ack ()
  (list 200 (cons "wuzapi_status" 200)
        (cons "data" (list (cons "success" t) (cons "data" (list (cons "Id" "fixture-id")))))))
(ert-deftest wa-delivery-acceptance-needs-provider-id ()
  (should (whatsapp--send-accepted-p (wa-delivery-ack)))
  (should-not (whatsapp--send-accepted-p (list 200 (cons "wuzapi_status" 200)))))
(ert-deftest wa-delivery-conflicting-ids-refused ()
  (let* ((ack (wa-delivery-ack)) (provider (cdr (assoc "data" (cdr ack))))
         (data (assoc "data" provider)))
    (setcdr data (append (cdr data) (list (cons "ID" "other-id"))))
    (should-not (whatsapp--send-accepted-p ack))))
(ert-deftest wa-delivery-nested-failure-refused ()
  (let* ((ack (wa-delivery-ack)) (provider (cdr (assoc "data" (cdr ack))))
         (data (assoc "data" provider)))
    (setcdr data (append (cdr data) (list (cons "success" nil))))
    (should-not (whatsapp--send-accepted-p ack))))
(ert-deftest wa-delivery-top-error-refused ()
  (should-not (whatsapp--send-accepted-p (append (wa-delivery-ack) (list (cons "error" nil))))))
(ert-deftest wa-delivery-text-always-uses-owned-worker ()
  (let ((whatsapp-use-read-worker nil) call)
    (cl-letf (((symbol-function 'whatsapp--read-worker) (lambda (&rest args) (setq call args)))
              ((symbol-function 'whatsapp--url-request-async) (lambda (&rest _) (ert-fail "Legacy URL POST used"))))
      (whatsapp--request-async "POST" "/send" '((body . "text")) #'ignore)
      (should (equal (car call) "/send")) (should (equal (nth 2 call) '((body . "text")))))))
(ert-deftest wa-delivery-uncertain-send-retains-draft ()
  (with-temp-buffer
    (whatsapp-chat-mode)
    (setq whatsapp-chat--jid "551100000001" whatsapp-chat--target "551100000001")
    (let ((whatsapp-auto-load-images nil))
      (whatsapp-chat--render nil) (insert "keep this")
      (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _data callback) (funcall callback '(200 ("wuzapi_status" . 200))))))
        (whatsapp-chat-send-input)
        (should (equal (whatsapp-chat--current-input) "keep this"))
        (should-not whatsapp-chat--send-pending)))))
(ert-deftest wa-delivery-pale-does-not-launch-mpv-implicitly ()
  (let ((whatsapp-video-backend 'pale))
    (cl-letf (((symbol-function 'whatsapp--play-bytes) (lambda (&rest _) (ert-fail "Silent external playback"))))
      (should-error (whatsapp-video-open "bytes" "video/mp4") :type 'user-error))))
(ert-deftest wa-delivery-explicit-mpv-dispatch ()
  (let ((whatsapp-video-backend 'mpv) result)
    (cl-letf (((symbol-function 'whatsapp--play-bytes) (lambda (&rest args) (setq result args))))
      (whatsapp-video-open "bytes" "video/mp4") (should (equal result '("bytes" "video/mp4"))))))
(ert-deftest wa-delivery-gif-does-not-default-to-mpv ()
  (let (opened)
    (cl-letf (((symbol-function 'whatsapp-gif-open) (lambda (bytes) (setq opened bytes)))
              ((symbol-function 'whatsapp--play-bytes) (lambda (&rest _) (ert-fail "External GIF playback"))))
      (whatsapp--open-bytes "fixture" "image/gif") (should (equal opened "fixture")))))
(defun wa-delivery-gif-fixture (&optional count)
  (concat (string-as-unibyte "GIF89a")
          (unibyte-string 1 0 1 0 128 0 0 0 0 0 255 255 255)
          (apply #'concat (make-list (or count 1) (unibyte-string 44 0 0 0 0 1 0 1 0 0 2 2 76 1 0)))
          (unibyte-string 59)))
(ert-deftest wa-delivery-gif-structure-and-frame-count ()
  (should (equal (whatsapp--gif-info (wa-delivery-gif-fixture 2)) '(1 1 2))))
(ert-deftest wa-delivery-gif-truncated-refused ()
  (should-error (whatsapp--gif-info (substring (wa-delivery-gif-fixture) 0 -1)) :type 'user-error))
(ert-deftest wa-delivery-gif-frame-budget ()
  (should-error (whatsapp--gif-info (wa-delivery-gif-fixture 121)) :type 'user-error))
(ert-deftest wa-delivery-gif-trailing-content-refused ()
  (should-error (whatsapp--gif-info (concat (wa-delivery-gif-fixture) "junk")) :type 'user-error))
(ert-deftest wa-delivery-gif-canvas-budget ()
  (let ((bytes (wa-delivery-gif-fixture)))
    (aset bytes 6 255) (aset bytes 7 255)
    (should-error (whatsapp--gif-info bytes) :type 'user-error)))
(ert-deftest wa-delivery-image-retry-is-account-scoped ()
  (let ((whatsapp--media-pending (make-hash-table :test 'equal))
        (whatsapp-bridge-token "fixture") (whatsapp-bridge-url "http://127.0.0.1:7337") scheduled)
    (with-temp-buffer
      (whatsapp-chat-mode) (setq whatsapp-chat--jid "one")
      (let ((key (whatsapp--media-key "image" "image")) (other '(different account chat image image)))
        (puthash key 'failed whatsapp--media-pending) (puthash other 'failed whatsapp--media-pending)
        (cl-letf (((symbol-function 'whatsapp-chat--schedule-prefetch) (lambda () (setq scheduled t)))
                  ((symbol-function 'whatsapp--request-async) (lambda (&rest _) (ert-fail "Unexpected direct request"))))
          (whatsapp-retry-images))
        (should scheduled) (should-not (gethash key whatsapp--media-pending))
        (should (eq (gethash other whatsapp--media-pending) 'failed))))))
(ert-deftest wa-delivery-panel-does-not-print-provider-secrets ()
  (with-temp-buffer
    (setq whatsapp--transport-data '(("token" . "PRIVATE-SECRET") ("connection_state" . "yes")
                                     ("jid" . "PRIVATE-IDENTITY") ("messages_ingested" . 5)))
    (whatsapp--transport-render)
    (should-not (string-match-p "PRIVATE" (buffer-string)))
    (should (string-match-p "Connection: yes" (buffer-string)))))
(ert-deftest wa-delivery-panel-does-not-make-network-calls-on-render ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'whatsapp--request-async) (lambda (&rest _) (ert-fail "Rendering requested network"))))
      (whatsapp--transport-render))))
(ert-deftest wa-delivery-repair-cancel-sends-no-request ()
  (with-temp-buffer
    (setq whatsapp--transport-origin (whatsapp--origin-key))
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
              ((symbol-function 'whatsapp--request-async) (lambda (&rest _) (ert-fail "Repair despite cancellation"))))
      (whatsapp-repair-incoming))))
(provide 'delivery-tests)
