;;; navigation-tests.el --- RC4 root navigation and redraw regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)

(defun wa-rc4-chat (id &optional unread name)
  (list (cons "jid" (format "%s" id)) (cons "name" (or name (format "Contact %s" id)))
        (cons "last" "preview-text") (cons "unread" (or unread 0))))

(ert-deftest wa-rc4-unread-count-updates-one-row-not-entire-root ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let* ((whatsapp--selected-chat nil)
           (old (list (wa-rc4-chat "a") (wa-rc4-chat "b")))
           (new (list (wa-rc4-chat "a" 1) (wa-rc4-chat "b")))
           (insert-row (symbol-function 'whatsapp-root--insert-row)) (calls 0))
      (whatsapp-root--render old)
      (goto-char (whatsapp-root--chat-position "b"))
      (cl-letf (((symbol-function 'erase-buffer) (lambda () (ert-fail "Unread changed layout")))
                ((symbol-function 'whatsapp-root--insert-row)
                 (lambda (chat width) (cl-incf calls) (funcall insert-row chat width))))
        (whatsapp-root--update new))
      (should (= calls 1))
      (should (string-match-p "2 chats · 1 unread" (buffer-string)))
      (should (equal "b" (get-text-property (point) 'whatsapp-jid))))))

(ert-deftest wa-rc4-offpage-unread-updates-summary-without-visible-row-insert ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let* ((whatsapp-root-page-size 2)
           (old (list (wa-rc4-chat "a") (wa-rc4-chat "b") (wa-rc4-chat "c")))
           (new (append (cl-subseq old 0 2) (list (wa-rc4-chat "c" 3)))))
      (whatsapp-root--render old)
      (cl-letf (((symbol-function 'erase-buffer) (lambda () (ert-fail "Full redraw")))
                ((symbol-function 'whatsapp-root--insert-row) (lambda (&rest _) (ert-fail "Offpage row inserted"))))
        (whatsapp-root--update new))
      (should (string-match-p "3 chats · 1 unread" (buffer-string)))
      (should-not (whatsapp-root--chat-position "c")))))

(ert-deftest wa-rc4-summary-digit-growth-preserves-row-position ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let* ((old (cl-loop for i from 1 to 12 collect (wa-rc4-chat i (if (< i 10) 1 0))))
           (new (copy-tree old)))
      (setcdr (assoc "unread" (nth 9 new)) 1)
      (whatsapp-root--render old)
      (goto-char (+ 2 (whatsapp-root--chat-position "12")))
      (whatsapp-root--update new)
      (should (string-match-p "12 chats · 10 unread" (buffer-string)))
      (should (equal "12" (get-text-property (point) 'whatsapp-jid)))
      (should (= (point) (+ 2 (whatsapp-root--chat-position "12")))))))

(ert-deftest wa-rc4-summary-unchanged-does-not-modify-text ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let ((rows (list (wa-rc4-chat "a"))))
      (whatsapp-root--render rows)
      (let ((tick (buffer-chars-modified-tick)))
        (whatsapp-root--update-summary rows)
        (should (= tick (buffer-chars-modified-tick)))))))

(ert-deftest wa-rc4-unread-filter-membership-still-changes-layout ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (setq whatsapp-root--filter 'unread)
    (whatsapp-root--render (list (wa-rc4-chat "a" 1) (wa-rc4-chat "b")))
    (whatsapp-root--update (list (wa-rc4-chat "a") (wa-rc4-chat "b" 1)))
    (should-not (whatsapp-root--chat-position "a"))
    (should (whatsapp-root--chat-position "b"))))

(ert-deftest wa-rc4-compact-row-is-one-line ()
  (with-temp-buffer
    (let ((whatsapp-root--compact t))
      (whatsapp-root--insert-row (wa-rc4-chat "a" 7) 38)
      (should (= (count-lines (point-min) (point-max)) 1))
      (should (string-match-p "\\[7\\]" (buffer-string)))
      (should-not (string-match-p "preview-text" (buffer-string)))
      (should (equal "a" (get-text-property (point-min) 'whatsapp-jid))))))

(ert-deftest wa-rc4-detailed-row-retains-preview ()
  (with-temp-buffer
    (let ((whatsapp-root--compact nil))
      (whatsapp-root--insert-row (wa-rc4-chat "a") 38)
      (should (= (count-lines (point-min) (point-max)) 2))
      (should (string-match-p "preview-text" (buffer-string))))))

(ert-deftest wa-rc4-density-toggle-preserves-filter-and-query ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let ((whatsapp--chats (list (wa-rc4-chat "a" 1) (wa-rc4-chat "b"))))
      (setq whatsapp-root--filter 'unread whatsapp-root--query "Contact" whatsapp-root--limit 120)
      (cl-letf (((symbol-function 'whatsapp--request) (lambda (&rest _) (ert-fail "Density requested network"))))
        (whatsapp-root-toggle-density))
      (should whatsapp-root--compact)
      (should (eq whatsapp-root--filter 'unread))
      (should (equal whatsapp-root--query "Contact"))
      (should (= whatsapp-root--limit 120))
      (should (whatsapp-root--chat-position "a"))
      (should-not (whatsapp-root--chat-position "b")))))

(ert-deftest wa-rc4-compact-initial-page-remains-bounded ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (setq whatsapp-root--compact t)
    (whatsapp-root--render (cl-loop for i from 1 to 300 collect (wa-rc4-chat i)))
    (should (whatsapp-root--chat-position "80"))
    (should-not (whatsapp-root--chat-position "81"))))

(ert-deftest wa-rc4-direct-filter-excludes-groups-and-keeps-search ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (setq whatsapp-root--filter 'direct whatsapp-root--query "Alice")
    (should (whatsapp-root--visible-p (wa-rc4-chat "1@s.whatsapp.net" 0 "Alice")))
    (should-not (whatsapp-root--visible-p (wa-rc4-chat "1@g.us" 0 "Alice")))
    (should-not (whatsapp-root--visible-p (wa-rc4-chat "2@s.whatsapp.net" 0 "Beto")))))

(ert-deftest wa-rc4-switch-sees-cache-beyond-page-and-requires-match ()
  (let ((whatsapp--chats (cl-loop for i from 1 to 300 collect (wa-rc4-chat i))) opened)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt choices _predicate match &rest _)
                 (should match)
                 (should (= (length choices) 300))
                 (car (nth 299 choices))))
              ((symbol-function 'whatsapp--request) (lambda (&rest _) (ert-fail "Synchronous lookup")))
              ((symbol-function 'whatsapp-open-chat) (lambda (jid) (setq opened jid))))
      (whatsapp-switch-chat))
    (should (equal opened "300"))))

(ert-deftest wa-rc4-switch-duplicate-names-remain-distinct ()
  (let ((whatsapp--chats (list (wa-rc4-chat "1" 0 "Alice") (wa-rc4-chat "2" 0 "Alice"))) opened)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_ choices &rest _)
                 (should-not (equal (caar choices) (caadr choices)))
                 (caadr choices)))
              ((symbol-function 'whatsapp-open-chat) (lambda (jid) (setq opened jid))))
      (whatsapp-switch-chat))
    (should (equal opened "2"))))

(ert-deftest wa-rc4-switch-annotations-are-bounded-and-flattened ()
  (let ((whatsapp--chats (list (wa-rc4-chat "1" 4 "Ali\nce"))))
    (setcdr (assoc "last" (car whatsapp--chats)) (concat "raw\n\u202e" (make-string 200 ?x)))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_ choices &rest _)
                 (let ((label (caar choices))
                       (annotation (funcall (plist-get completion-extra-properties :annotation-function) (caar choices))))
                   (should-not (string-match-p "[\n\u202e]" (concat label annotation)))
                   (should (< (string-width annotation) 100))
                   (should (string-match-p "4 unread" annotation))
                   label)))
              ((symbol-function 'whatsapp-open-chat) #'ignore))
      (whatsapp-switch-chat))))

(ert-deftest wa-rc4-switch-empty-cache-is-actionable-error ()
  (let ((whatsapp--chats nil))
    (should-error (whatsapp-switch-chat) :type 'user-error)))

(ert-deftest wa-rc4-switch-cancel-keeps-draft ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "unsent draft")
   (let ((whatsapp--chats (list (wa-rc4-chat "a"))))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil)))
               ((symbol-function 'whatsapp-open-chat) (lambda (&rest _) (ert-fail "Opened after cancel"))))
       (condition-case nil (whatsapp-switch-chat) (quit nil)))
     (should (equal "unsent draft" (whatsapp-chat--current-input))))))

(ert-deftest wa-rc4-new-bindings-do-not-replace-forward ()
  (should (eq (lookup-key whatsapp-chat-mode-map (kbd "C-c C-j")) #'whatsapp-switch-chat))
  (should (eq (lookup-key whatsapp-root-mode-map (kbd "d")) #'whatsapp-root-toggle-density))
  (should (eq (lookup-key whatsapp-chat-mode-map (kbd "C-c C-f")) #'whatsapp-chat-forward)))

(ert-deftest wa-rc4-version-is-valid-package-version ()
  (should (version-to-list whatsapp-version)))

;;; RC6: native regression tests for button semantics and window-scoped polling.
(ert-deftest wa-rc6-history-button-return-expands-and-retains-draft ()
  (whatsapp-workspace-test-chat
   (let ((whatsapp-history-page-size 1)
         (messages '((("id" . "old") ("text" . "earlier"))
                     (("id" . "new") ("text" . "recent")))))
     (insert "draft remains")
     (whatsapp-chat--render messages)
     (let ((button (whatsapp-workspace-test-button #'whatsapp-chat-show-older)))
       (should button)
       (goto-char (button-start button))
       (cl-letf (((symbol-function 'whatsapp-chat-send-input)
                  (lambda () (ert-fail "Return on button sent a message"))))
         (whatsapp-chat-return)))
     (should (string-match-p "earlier" (buffer-string)))
     (should (equal "draft remains" (whatsapp-chat--current-input))))))

(ert-deftest wa-rc6-button-identity-independent-of-label ()
  (with-temp-buffer
    (whatsapp--button "Any translated wording" #'whatsapp-chat-show-older)
    (let ((button (whatsapp-workspace-test-button #'whatsapp-chat-show-older)))
      (should button)
      (should (functionp (button-get button 'action)))
      (should (equal (button-label button) "Any translated wording")))))

(ert-deftest wa-rc6-visible-buffer-discovery-skips-iconified-and-hidden-frames ()
  (let (visited)
    (cl-letf (((symbol-function 'frame-list) (lambda () '(shown iconified hidden)))
              ((symbol-function 'frame-visible-p)
               (lambda (frame) (pcase frame ('shown t) ('iconified 'icon) (_ nil))))
              ((symbol-function 'window-list)
               (lambda (frame minibuf &rest _)
                 (push frame visited)
                 (should (eq minibuf 'no-minibuffer))
                 '(one two three)))
              ((symbol-function 'window-buffer)
               (lambda (window) (if (eq window 'three) 'second 'first)))
              ((symbol-function 'buffer-list) (lambda (&rest _) (ert-fail "Scanned unrelated buffers")))
              ((symbol-function 'get-buffer-window) (lambda (&rest _) (ert-fail "Scanned windows per buffer"))))
      (should (equal (whatsapp--visible-buffers) '(first second)))
      (should (equal visited '(shown))))))

(ert-deftest wa-rc6-visible-buffer-discovery-deduplicates-across-frames ()
  (cl-letf (((symbol-function 'frame-list) (lambda () '(one two)))
            ((symbol-function 'frame-visible-p) (lambda (_) t))
            ((symbol-function 'window-list) (lambda (&rest _) '(window)))
            ((symbol-function 'window-buffer) (lambda (_) 'shared)))
    (should (equal (whatsapp--visible-buffers) '(shared)))))

(ert-deftest wa-rc6-polling-does-not-enumerate-entire-buffer-list ()
  (with-temp-buffer
    (whatsapp-chat-mode)
    (let ((buffer (current-buffer)) (calls 0))
      (cl-letf (((symbol-function 'whatsapp--visible-buffers) (lambda () (list buffer)))
                ((symbol-function 'buffer-list) (lambda (&rest _) (ert-fail "Unbounded buffer scan")))
                ((symbol-function 'float-time) (lambda (&rest _) 100))
                ((symbol-function 'whatsapp-chat-refresh) (lambda (&rest _) (cl-incf calls))))
        (whatsapp--poll)
        (should (= calls 1))))))

(ert-deftest wa-rc6-polling-retains-failure-backoff ()
  (with-temp-buffer
    (whatsapp-chat-mode)
    (setq whatsapp--next-refresh 101)
    (let ((buffer (current-buffer)) (calls 0))
      (cl-letf (((symbol-function 'whatsapp--visible-buffers) (lambda () (list buffer)))
                ((symbol-function 'float-time) (lambda (&rest _) 100))
                ((symbol-function 'whatsapp-chat-refresh) (lambda (&rest _) (cl-incf calls))))
        (whatsapp--poll)
        (should (= calls 0))))))

(ert-deftest wa-rc6-polling-skips-closing-buffer ()
  (with-temp-buffer
    (whatsapp-chat-mode)
    (setq whatsapp--closing t)
    (let ((buffer (current-buffer)) (calls 0))
      (cl-letf (((symbol-function 'whatsapp--visible-buffers) (lambda () (list buffer)))
                ((symbol-function 'whatsapp-chat-refresh) (lambda (&rest _) (cl-incf calls))))
        (whatsapp--poll)
        (should (= calls 0))))))

(ert-deftest wa-rc6-polling-one-buffer-error-does-not-starve-root ()
  (let ((chat (generate-new-buffer " *rc6-chat*"))
        (root (generate-new-buffer " *rc6-root*")) (calls 0)
        (whatsapp-poll-interval 5))
    (unwind-protect
        (progn
          (with-current-buffer chat (whatsapp-chat-mode))
          (with-current-buffer root (whatsapp-root-mode))
          (cl-letf (((symbol-function 'whatsapp--visible-buffers) (lambda () (list chat root)))
                    ((symbol-function 'float-time) (lambda (&rest _) 100))
                    ((symbol-function 'whatsapp-chat-refresh) (lambda (&rest _) (error "secret-fixture")))
                    ((symbol-function 'whatsapp-root-refresh) (lambda (&rest _) (cl-incf calls))))
            (whatsapp--poll))
          (should (= calls 1))
          (with-current-buffer chat
            (should (= whatsapp--next-refresh 105))
            (should (stringp whatsapp--last-error))
            (should-not (string-match-p "secret-fixture" whatsapp--last-error))))
      (kill-buffer chat) (kill-buffer root))))

(ert-deftest wa-rc6-polling-skips-killed-window-buffer ()
  (let ((dead (generate-new-buffer " *rc6-dead*")))
    (kill-buffer dead)
    (cl-letf (((symbol-function 'whatsapp--visible-buffers) (lambda () (list dead))))
      (whatsapp--poll))))

(ert-deftest wa-rc6-no-visible-frames-produces-no-work ()
  (cl-letf (((symbol-function 'frame-list) (lambda () '(hidden)))
            ((symbol-function 'frame-visible-p) (lambda (_) nil))
            ((symbol-function 'window-list) (lambda (&rest _) (ert-fail "Hidden frame scanned"))))
    (should-not (whatsapp--visible-buffers))))

(provide 'navigation-tests)
;;; navigation-tests.el ends here

;;; RC7 account-pair regression checks (all network entry points are stubbed).
(defmacro wa-rc7-launch-context (&rest body)
  `(let ((process-environment (copy-sequence process-environment))
         (whatsapp-bridge-url "https://init.example.invalid")
         (whatsapp-bridge-token "init-token")
         (whatsapp--workspace-active nil)
         (whatsapp-media-player "mpv"))
     (setenv "WHATSAPPEL_TOKEN" nil)
     (setenv "WHATSAPPEL_BRIDGE_URL" nil)
     (cl-letf (((symbol-function 'whatsapp) #'ignore)
               ((symbol-function 'whatsapp--ensure-polling) #'ignore))
       ,@body)))

(ert-deftest wa-rc7-launch-retains-init-only-pair ()
  (wa-rc7-launch-context
   (whatsapp-launch)
   (should (equal whatsapp-bridge-url "https://init.example.invalid"))
   (should (equal whatsapp-bridge-token "init-token"))))

(ert-deftest wa-rc7-external-pair-overrides-both-init-settings ()
  (wa-rc7-launch-context
   (setenv "WHATSAPPEL_TOKEN" "external-token")
   (setenv "WHATSAPPEL_BRIDGE_URL" "https://external.example.invalid")
   (whatsapp-launch)
   (should (equal whatsapp-bridge-url "https://external.example.invalid"))
   (should (equal whatsapp-bridge-token "external-token"))))

(ert-deftest wa-rc7-token-only-never-borrows-init-origin ()
  (wa-rc7-launch-context
   (setenv "WHATSAPPEL_TOKEN" "external-token")
   (whatsapp-launch)
   (should (equal whatsapp-bridge-url "http://127.0.0.1:7337"))
   (should (equal whatsapp-bridge-token "external-token"))))

(ert-deftest wa-rc7-url-only-never-borrows-init-token ()
  (wa-rc7-launch-context
   (setenv "WHATSAPPEL_BRIDGE_URL" "https://external.example.invalid")
   (should-error (whatsapp-launch) :type 'user-error)
   (should (equal whatsapp-bridge-token "init-token"))
   (should (equal whatsapp-bridge-url "https://init.example.invalid"))
   (should-not whatsapp--workspace-active)))

(ert-deftest wa-rc7-empty-token-does-not-fall-back-to-init ()
  (wa-rc7-launch-context
   (setenv "WHATSAPPEL_TOKEN" "")
   (should-error (whatsapp-launch) :type 'user-error)
   (should (equal whatsapp-bridge-token "init-token"))))

(ert-deftest wa-rc7-launch-validation-precedes-network ()
  (wa-rc7-launch-context
   (setenv "WHATSAPPEL_TOKEN" "invalid token")
   (cl-letf (((symbol-function 'whatsapp) (lambda () (ert-fail "Network/UI started before validation"))))
     (should-error (whatsapp-launch) :type 'user-error))))
