;;; profiles-ui-smoke.el --- actual graphical fixture capture -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
;; Run only as a separate `emacs -Q -L . -l tests/profiles-ui-smoke.el` process.
;; Does not run during ordinary application startup. No generated screenshot claim.
(require 'whatsapp)
(require 'cl-lib)
(setq debug-on-error t)
(unless (display-graphic-p) (error "Graphical Emacs with x-export-frames is required"))
(unless (fboundp 'x-export-frames) (error "This build cannot export native frame PNGs"))
(let* ((output (getenv "WHATSAPPEL_UI_OUTPUT"))
       (whatsapp-bridge-url "http://127.0.0.1:1") (whatsapp-bridge-token "SYNTHETIC-NOT-AN-ACCOUNT")
       (whatsapp-auto-poll nil) (whatsapp-auto-load-images nil)
       (whatsapp-profile-photos nil) (whatsapp-profile-presence-enabled nil)
       (whatsapp-profiles--scope (whatsapp--origin-key))
       (whatsapp--chats '((("jid" . "15550000001") ("name" . "DEMO · Design studio") ("unread" . 3) ("last" . "Synthetic text. Not connected."))
                          (("jid" . "15550000002") ("name" . "DEMO · Ana ç日本") ("unread" . 1) ("last" . "Photo unavailable: initials fallback."))
                          (("jid" . "120000000000@g.us") ("name" . "DEMO · Community") ("unread" . 0) ("last" . "A group is not a remote online status.")))))
  (unless (and output (file-name-absolute-p output) (file-directory-p output)
               (not (file-symlink-p output)))
    (error "Provide an existing private output directory in WHATSAPPEL_UI_OUTPUT"))
  (cl-labels ((blocked (&rest _) (error "DEMO forbids network and sending"))
              (capture (name)
                (redisplay t) (sleep-for .15)
                (let ((coding-system-for-write 'binary))
                  (write-region (x-export-frames nil 'png) nil (expand-file-name name output) nil 'silent))))
    (cl-letf (((symbol-function 'whatsapp--request-async) #'blocked)
              ((symbol-function 'whatsapp--request) #'blocked)
              ((symbol-function 'whatsapp-profiles--start-child) #'blocked)
              ((symbol-function 'whatsapp-profiles-start) (lambda () nil)))
      (tool-bar-mode -1)
      (set-frame-name "WhatsAppel RC9 — OFFLINE SYNTHETIC DEMO")
      (set-frame-size (selected-frame) 124 38)
      (switch-to-buffer (whatsapp--root-buffer))
      (whatsapp-root--render whatsapp--chats)
      (capture "demo-wide-root.png")
      (switch-to-buffer (whatsapp--chat-buffer "15550000001"))
      (whatsapp-chat--render '((("id" . "demo-1") ("kind" . "text") ("name" . "DEMO")
                                ("text" . "Synthetic conversation. No real account or recipient."))))
      (goto-char (point-max)) (insert "DEMO draft: will never be sent")
      (whatsapp-profiles--update-header)
      (capture "demo-conversation.png")
      (whatsapp-contact-info "15550000001")
      (capture "demo-contact-info.png")
      (set-frame-size (selected-frame) 62 30)
      (switch-to-buffer (whatsapp--root-buffer))
      (whatsapp-root--render whatsapp--chats)
      (capture "demo-narrow-root.png")
      (text-scale-increase 1)
      (whatsapp-root--render whatsapp--chats)
      (capture "demo-large-font.png")
      (with-temp-file (expand-file-name "native-ui-result.txt" output)
        (insert (format "Executed native graphical fixture capture with Emacs %s. Five frames exported. No provider or account verification.\n" emacs-version))))))
(kill-emacs 0)
