;;; profiles-tests.el --- Native profile workspace regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)

(defmacro wa-profile-fixture (&rest body)
  `(let* ((whatsapp-bridge-url "http://127.0.0.1:7337")
          (whatsapp-bridge-token "synthetic-profile-token")
          (whatsapp-profiles--scope (whatsapp--origin-key))
          (whatsapp-profiles--epoch "fixture-1") (whatsapp-profiles--generation 0)
          (whatsapp-profiles--meta (make-hash-table :test 'equal))
          (whatsapp-profiles--photos (make-hash-table :test 'equal))
          (whatsapp-profiles--pending (make-hash-table :test 'equal))
          (whatsapp-profiles--queue nil) (whatsapp-profiles--processes nil)
          (whatsapp-profiles--buffers nil) (whatsapp-profiles--photo-order nil)
          (whatsapp-profiles--consent-origin nil) (whatsapp-profiles--timer nil)
          (whatsapp-profiles--capability 'ready) (whatsapp-profiles--next-snapshot 0)
          (whatsapp-profile-photos t) (whatsapp-profile-presence-enabled nil)
          (whatsapp-auto-poll nil) (whatsapp-auto-load-images nil)
          (whatsapp--selected-chat "123456789"))
     (unwind-protect (progn ,@body)
       (when (timerp whatsapp-profiles--timer) (cancel-timer whatsapp-profiles--timer))
       (whatsapp-profiles--reset))))

(ert-deftest wa-rc9-presence-unknown-is-not-offline ()
  (wa-profile-fixture (should (equal (whatsapp-profiles--presence-label "123456789") "Status unavailable"))))
(ert-deftest wa-rc9-positive-presence-expires-without-invented-offline ()
  (wa-profile-fixture
   (puthash "123456789" (list :availability "online" :available-until (+ (float-time) 10)) whatsapp-profiles--meta)
   (should (equal (whatsapp-profiles--presence-label "123456789") "Online"))
   (puthash "123456789" '(:availability "online" :available-until 1) whatsapp-profiles--meta)
   (should (equal (whatsapp-profiles--presence-label "123456789") "Status unavailable"))))
(ert-deftest wa-rc9-recording-expires-independently ()
  (wa-profile-fixture
   (puthash "123456789" (list :activity "recording" :activity-until (+ (float-time) 2)) whatsapp-profiles--meta)
   (should (equal (whatsapp-profiles--presence-label "123456789") "Recording audio…"))
   (puthash "123456789" '(:activity "recording" :activity-until 1) whatsapp-profiles--meta)
   (should (equal (whatsapp-profiles--presence-label "123456789") "Status unavailable"))))
(ert-deftest wa-rc9-group-is-not-an-online-contact ()
  (wa-profile-fixture (should (equal (whatsapp-profiles--presence-label "123456789@g.us") "Group conversation"))))
(ert-deftest wa-rc9-account-change-hides-old-presence ()
  (wa-profile-fixture
   (puthash "123456789" (list :availability "online" :available-until (+ (float-time) 20)) whatsapp-profiles--meta)
   (let ((whatsapp-bridge-token "a-different-account"))
     (should (equal (whatsapp-profiles--presence-label "123456789") "Status unavailable")))))
(ert-deftest wa-rc9-old-chat-refuses-new-account-details ()
  (wa-profile-fixture
   (with-temp-buffer
     (whatsapp-chat-mode)
     (setq whatsapp-chat--jid "123456789" whatsapp--read-origin '(old-account))
     (should-error (whatsapp-profile-at-point) :type 'user-error))))
(ert-deftest wa-rc9-photo-lookup-does-not-decode ()
  (wa-profile-fixture
   (cl-letf (((symbol-function 'create-image) (lambda (&rest _) (ert-fail "Unexpected native decoder"))))
     (should-not (whatsapp-profiles--photo "123456789")))))
(ert-deftest wa-rc9-expired-photo-is-never-returned ()
  (wa-profile-fixture
   (puthash '("123456789" . avatar) '(:image (image :type png) :expires 1) whatsapp-profiles--photos)
   (should-not (whatsapp-profiles--photo "123456789"))))
(ert-deftest wa-rc9-queue-deduplicates-and-bounds-work ()
  (wa-profile-fixture
   (dotimes (_ 30) (whatsapp-profiles--enqueue 'avatar "123456789"))
   (should (= (length whatsapp-profiles--queue) 1))
   (dotimes (i 30) (whatsapp-profiles--enqueue 'avatar (number-to-string (+ 100000 i))))
   (should (= (length whatsapp-profiles--queue) 16))))
(ert-deftest wa-rc9-pending-task-is-not-requeued ()
  (wa-profile-fixture
   (puthash '(avatar "123456789") t whatsapp-profiles--pending)
   (whatsapp-profiles--enqueue 'avatar "123456789")
   (should-not whatsapp-profiles--queue)))
(ert-deftest wa-rc9-reset-removes-photos-metadata-and-consent ()
  (wa-profile-fixture
   (setq whatsapp-profiles--consent-origin whatsapp-profiles--scope)
   (puthash "123456789" '(:about "private fixture") whatsapp-profiles--meta)
   (whatsapp-profiles--enqueue 'about "123456789")
   (whatsapp-profiles--reset)
   (should-not whatsapp-profiles--consent-origin)
   (should-not whatsapp-profiles--queue)
   (should (= 0 (hash-table-count whatsapp-profiles--meta)))))
(ert-deftest wa-rc9-photo-property-update-retains-text-and-draft-marker ()
  (wa-profile-fixture
   (with-temp-buffer
     (whatsapp-chat-mode) (setq whatsapp-chat--jid "123456789")
     (let ((inhibit-read-only t))
       (whatsapp-profiles--insert-avatar "123456789")
       (insert "\n")
       (setq whatsapp-chat--input-marker (copy-marker (point)))
       (insert "draft unchanged"))
     (let ((text (buffer-substring-no-properties (point-min) (point-max)))
           (position (marker-position whatsapp-chat--input-marker)))
       (whatsapp-profiles--paint-avatars "123456789")
       (should (equal text (buffer-substring-no-properties (point-min) (point-max))))
       (should (= position (marker-position whatsapp-chat--input-marker)))))))
(ert-deftest wa-rc9-contact-string-layout-controls-removed ()
  (let ((value (propertize "Ali\n\t\u202e<text>" 'keymap 'hostile)))
    (should-not (text-properties-at 0 (whatsapp-profiles--safe value)))
    (should-not (string-match-p "[\n\t\u202e]" (whatsapp-profiles--safe value)))))
(ert-deftest wa-rc9-long-name-is-bounded ()
  (should (= 80 (length (whatsapp-profiles--safe (make-string 100000 ?a) 80)))))
(ert-deftest wa-rc9-photo-avatar-return-action-is-contact-info-not-send ()
  (should (eq (lookup-key whatsapp-profile-avatar-map (kbd "RET")) #'whatsapp-profile-at-point))
  (should (eq (lookup-key whatsapp-profile-avatar-map [mouse-1]) #'whatsapp-profile-click)))
(ert-deftest wa-rc9-row-avatar-has-independent-action ()
  (wa-profile-fixture
   (with-temp-buffer
     (whatsapp-root-mode)
     (let ((inhibit-read-only t))
       (whatsapp-root--insert-row '(("jid" . "123456789") ("name" . "Fixture Name")) 38))
     (should (equal (get-text-property (point-min) 'whatsapp-profile-jid) "123456789"))
     (should (eq (get-text-property (point-min) 'keymap) whatsapp-profile-avatar-map)))))
(ert-deftest wa-rc9-selection-does-not-delete-rows ()
  (wa-profile-fixture
   (with-temp-buffer
     (whatsapp-root-mode)
     (let ((inhibit-read-only t))
       (whatsapp-root--insert-row '(("jid" . "123456789") ("name" . "Fixture Name")) 38))
     (let ((text (buffer-substring-no-properties (point-min) (point-max))))
       (whatsapp-root--select-only "987654321")
       (should (equal text (buffer-substring-no-properties (point-min) (point-max))))))))
(ert-deftest wa-rc9-no-contact-subscription-without-consent ()
  (wa-profile-fixture
   (let (started)
     (cl-letf (((symbol-function 'whatsapp-profiles--visible) (lambda () '("123456789")))
               ((symbol-function 'whatsapp-profiles--user-work-p) (lambda () nil))
               ((symbol-function 'display-graphic-p) (lambda (&rest _) nil))
               ((symbol-function 'whatsapp-profiles--start-child) (lambda (task) (push task started))))
       (whatsapp-profiles--tick))
     (should-not (assq 'subscribe started)))))
(ert-deftest wa-rc9-pending-message-work-defers-profile-work ()
  (wa-profile-fixture
   (cl-letf (((symbol-function 'whatsapp-profiles--visible) (lambda () '("123456789")))
             ((symbol-function 'whatsapp-profiles--user-work-p) (lambda () t))
             ((symbol-function 'whatsapp-profiles--start-child) (lambda (_) (ert-fail "Profile stole user-work priority"))))
     (whatsapp-profiles--tick))))
(ert-deftest wa-rc9-hidden-profiles-start-no-worker ()
  (wa-profile-fixture
   (cl-letf (((symbol-function 'whatsapp-profiles--visible) (lambda () nil))
             ((symbol-function 'whatsapp-profiles--start-child) (lambda (_) (ert-fail "Hidden view requested enrichment"))))
     (whatsapp-profiles--tick))))
(ert-deftest wa-rc9-epoch-change-removes-old-avatar ()
  (wa-profile-fixture
   (puthash '("123456789" . avatar) '(:image (image :type png) :expires 9999999999) whatsapp-profiles--photos)
   (whatsapp-profiles--accept '(snapshot ("123456789"))
                             '(("status" . 200) ("body" ("version" . 1) ("epoch" . "fixture-2") ("profiles" . nil))))
   (should (= 0 (hash-table-count whatsapp-profiles--photos)))))
(ert-deftest wa-rc9-missing-backend-capability-falls-back ()
  (wa-profile-fixture
   (whatsapp-profiles--accept '(capabilities nil) '(("status" . 404) ("body" ("state" . "unsupported"))))
   (should (eq whatsapp-profiles--capability 'unavailable))))
(ert-deftest wa-rc9-theme-is-buffer-local ()
  (let ((original (face-attribute 'default :background nil t)))
    (wa-profile-fixture (with-temp-buffer (whatsapp-root-mode)
                         (should (local-variable-p 'face-remapping-alist))
                         (should-not display-line-numbers)))
    (should (equal original (face-attribute 'default :background nil t)))))
(ert-deftest wa-rc9-forward-keybinding-preserved ()
  (should (eq (lookup-key whatsapp-chat-mode-map (kbd "C-c C-f")) #'whatsapp-chat-forward)))

(ert-deftest wa-rc9-delayed-profile-worker-keeps-composer-and-heartbeat-live ()
  "Real native sockets and actual Python process; five-second provider fixture."
  (unless (executable-find whatsapp-python-program) (ert-skip "Python required"))
  (wa-profile-fixture
   (save-window-excursion
     (let (server clients send-timers heartbeat buffer (ticks 0) (requests 0)
           (whatsapp-workspace-sidebar nil))
       (unwind-protect
           (progn
             (setq server
                   (make-network-process
                    :name "wa-profile-delayed" :server t :family 'ipv4 :host "127.0.0.1" :service t
                    :noquery t :coding 'binary
                    :filter (lambda (p text)
                              (cl-pushnew p clients)
                              (process-put p 'raw (concat (process-get p 'raw) text))
                              (when (and (not (process-get p 'sent)) (string-match-p "\r\n\r\n" (process-get p 'raw)))
                                (process-put p 'sent t) (cl-incf requests)
                                (push (run-at-time
                                       5 nil (lambda ()
                                               (when (process-live-p p)
                                                 (let ((body "{\"version\":1,\"epoch\":\"fixture-1\"}"))
                                                   (process-send-string p (format "HTTP/1.1 200 OK\r\nContent-Length: %d\r\nConnection: close\r\n\r\n%s" (length body) body))
                                                   (process-send-eof p))))) send-timers)))))
             (setq whatsapp-bridge-url (format "http://127.0.0.1:%s" (process-contact server :service))
                   whatsapp-profiles--scope (whatsapp--origin-key))
             (setq buffer (generate-new-buffer " *wa-profile-delayed-chat*"))
             (with-current-buffer buffer
               (whatsapp-chat-mode) (setq whatsapp-chat--jid "123456789" whatsapp-chat--target "123456789")
               (whatsapp-chat--render nil))
             (pop-to-buffer buffer) (goto-char (point-max)) (insert "draft before photo reply")
             (setq heartbeat (run-at-time .01 .01 (lambda () (cl-incf ticks))))
             (whatsapp-profiles--start-child '(capabilities nil))
             (should (equal (whatsapp-chat--current-input) "draft before photo reply"))
             (let ((deadline (+ (float-time) 9)))
               (while (and whatsapp-profiles--processes (< (float-time) deadline))
                 (accept-process-output nil .02)))
             (should (> ticks 20)) (should (= requests 1))
             (should-not whatsapp-profiles--processes)
             (should (equal (whatsapp-chat--current-input) "draft before photo reply")))
         (when heartbeat (cancel-timer heartbeat))
         (dolist (timer send-timers) (cancel-timer timer))
         (dolist (proc clients) (when (process-live-p proc) (delete-process proc)))
         (when (and server (process-live-p server)) (delete-process server))
         (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(provide 'profiles-tests)
;;; profiles-tests.el ends here
