;;; recipient-ui-tests.el --- RC13 routing and quiet UI regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)
(require 'performance-tests)
(require 'delivery-tests)

(ert-deftest wa-rc13-lid-target-is-not-a-phone ()
  (should (equal (whatsapp--target-of-jid "123456789012345@lid") "123456789012345@lid")))
(ert-deftest wa-rc13-phone-and-group-targets-remain-compatible ()
  (dolist (pair '(("551100000001@s.whatsapp.net" . "551100000001")
                  ("551100000001@c.us" . "551100000001")
                  ("551100000001" . "551100000001")
                  ("120000000000@g.us" . "120000000000@g.us")
                  ("opaque@example.test" . "opaque@example.test")))
    (should (equal (whatsapp--target-of-jid (car pair)) (cdr pair)))))
(ert-deftest wa-rc13-empty-target-is-rejected ()
  (should-error (whatsapp--target-of-jid "") :type 'user-error)
  (should-error (whatsapp--target-of-jid nil) :type 'user-error))
(ert-deftest wa-rc13-send-recomputes-stale-lid-target ()
  (wa-rc2-chat
   (setq whatsapp-chat--jid "123456789012345@lid" whatsapp-chat--target "123456789012345")
   (whatsapp-chat--render nil) (insert "local fixture")
   (let (payload callback (calls 0))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_method _path body cb) (cl-incf calls) (setq payload body callback cb))))
       (whatsapp-chat-send-input)
       (should (= calls 1))
       (should (equal (cdr (assoc "to" payload)) "123456789012345@lid"))
       (should (equal (whatsapp-chat--current-input) "local fixture"))
       (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'sending))
       (should-error (whatsapp-chat-send-input) :type 'user-error)
       (should (= calls 1))
       (funcall callback '(503 ("uncertain" . t)))
       (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'unconfirmed))
       (should (equal (whatsapp-chat--current-input) "local fixture"))))))
(ert-deftest wa-rc13-accepted-note-survives-stale-history ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "own fixture")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async) (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh) #'ignore))
       (whatsapp-chat-send-input) (funcall callback (wa-delivery-ack)))
     (should (equal (whatsapp-chat--current-input) ""))
     (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'accepted))
     (should (string-match-p "awaiting history/receipt"
                             (overlay-get whatsapp-chat--outgoing-overlay 'before-string)))
     (whatsapp-chat--render nil)
     (whatsapp-chat--reconcile-outgoing nil)
     (should (= (length whatsapp-chat--outgoing) 1))
     (should (overlayp whatsapp-chat--outgoing-overlay)))))
(ert-deftest wa-rc13-accepted-note-deduplicates-by-provider-id-not-text ()
  (wa-rc2-chat
   (whatsapp-chat--render nil)
   (let ((entry (whatsapp-chat--begin-outgoing "fixture" (whatsapp--origin-key) "fixture")))
     (whatsapp-chat--finish-outgoing entry (wa-delivery-ack))
     (whatsapp-chat--reconcile-outgoing '((("id" . "other") ("me" . t) ("text" . "fixture"))))
     (should (= (length whatsapp-chat--outgoing) 1))
     (whatsapp-chat--reconcile-outgoing '((("id" . "fixture-id") ("me" . nil))))
     (should (= (length whatsapp-chat--outgoing) 1))
     (whatsapp-chat--reconcile-outgoing '((("id" . "fixture-id") ("me" . t) ("delivery" . "accepted"))))
     (should-not whatsapp-chat--outgoing)
     (should-not whatsapp-chat--outgoing-overlay))))
(ert-deftest wa-rc13-note-keeps-draft-and-undo-positions ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (buffer-enable-undo) (insert "keep draft")
   (let ((before (buffer-string)) (position (point)) (marker (marker-position whatsapp-chat--input-marker))
         (undo buffer-undo-list) (modified (buffer-modified-p)))
     (whatsapp-chat--begin-outgoing "fixture" (whatsapp--origin-key) "fixture")
     (should (equal before (buffer-string))) (should (= position (point)))
     (should (= marker (marker-position whatsapp-chat--input-marker)))
     (should (eq undo buffer-undo-list)) (should (eq modified (buffer-modified-p))))))
(ert-deftest wa-rc13-note-reuses-one-overlay ()
  (wa-rc2-chat
   (whatsapp-chat--render nil)
   (whatsapp-chat--begin-outgoing "fixture" (whatsapp--origin-key) "fixture")
   (let ((overlay whatsapp-chat--outgoing-overlay) (chars (buffer-chars-modified-tick)))
     (dotimes (_ 200) (whatsapp-chat--paint-outgoing))
     (should (eq overlay whatsapp-chat--outgoing-overlay))
     (should (= chars (buffer-chars-modified-tick)))
     (should (= 1 (cl-count-if (lambda (o) (overlay-get o 'whatsapp-outgoing-note))
                               (append (car (overlay-lists)) (cdr (overlay-lists)))))))))
(ert-deftest wa-rc13-note-count-is-bounded ()
  (wa-rc2-chat
   (dotimes (i 16) (whatsapp-chat--begin-outgoing (format "fixture-%d" i) (whatsapp--origin-key) "fixture"))
   (should-error (whatsapp-chat--begin-outgoing "too many" (whatsapp--origin-key) "fixture") :type 'user-error)))
(ert-deftest wa-rc13-note-bytes-are-bounded ()
  (wa-rc2-chat
   (should-error (whatsapp-chat--begin-outgoing (make-string (* 256 1024) ?é) (whatsapp--origin-key) "fixture") :type 'user-error)
   (should-not whatsapp-chat--outgoing)))
(ert-deftest wa-rc13-unconfirmed-draft-cannot-accidentally-resend ()
  (wa-rc2-chat
   (let ((entry (whatsapp-chat--begin-outgoing "fixture" (whatsapp--origin-key) "fixture")))
     (whatsapp-chat--finish-outgoing entry '(200 ("wuzapi_status" . 200)))
     (should-error (whatsapp-chat--begin-outgoing "fixture" (whatsapp--origin-key) "fixture") :type 'user-error))))
(ert-deftest wa-rc13-late-account-callback-cannot-clear-new-draft ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "first account draft")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async) (lambda (_m _p _d cb) (setq callback cb))))
       (whatsapp-chat-send-input))
     (let ((whatsapp-bridge-token "second-account"))
       (funcall callback (wa-delivery-ack))
       (should (equal (whatsapp-chat--current-input) "first account draft"))
       (should-not whatsapp-chat--outgoing-overlay)))))
(ert-deftest wa-rc13-newer-draft-survives-acknowledgement ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "draft")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async) (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh) #'ignore))
       (whatsapp-chat-send-input) (insert " more") (funcall callback (wa-delivery-ack))
       (should (equal (whatsapp-chat--current-input) "draft more"))
       (funcall callback (wa-delivery-ack))
       (should (= 1 (length whatsapp-chat--outgoing)))))))
(ert-deftest wa-rc13-clear-notes-is-explicit-and-not-a-send ()
  (wa-rc2-chat
   (let ((entry (whatsapp-chat--begin-outgoing "fixture" (whatsapp--origin-key) "fixture")))
     (should-error (whatsapp-clear-send-notes) :type 'user-error)
     (whatsapp-chat--finish-outgoing entry '(nil ("uncertain" . t)))
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
       (whatsapp-clear-send-notes) (should whatsapp-chat--outgoing))
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
               ((symbol-function 'whatsapp--request-async) (lambda (&rest _) (ert-fail "Dismiss must not send"))))
       (whatsapp-clear-send-notes) (should-not whatsapp-chat--outgoing)))))
(ert-deftest wa-rc13-clean-faces-are-buffer-local-and-idempotent ()
  (let ((old (face-attribute 'highlight :underline nil 'default)) (outside face-remapping-alist))
    (with-temp-buffer
      (whatsapp-root-mode)
      (let ((count (length whatsapp-profiles--face-cookies)))
        (dotimes (_ 25) (whatsapp-profiles--setup-buffer))
        (should (= count (length whatsapp-profiles--face-cookies))))
      (should-not display-line-numbers)
      (dolist (face '(default button highlight whatsapp-profile-selection whatsapp-contact))
        (should (cl-some (lambda (entry)
                           (and (listp entry) (plist-member entry :underline)
                                (null (plist-get entry :underline))
                                (plist-member entry :overline) (null (plist-get entry :overline))
                                (plist-member entry :box) (null (plist-get entry :box))))
                         (cdr (assq face face-remapping-alist))))))
    (should (equal old (face-attribute 'highlight :underline nil 'default)))
    (should (equal outside face-remapping-alist))))
(ert-deftest wa-rc13-hover-and-selection-never-add-line-characters ()
  (with-temp-buffer
    (whatsapp-root-mode)
    (let ((whatsapp--chats '((("jid" . "1@lid") ("name" . "Alice"))
                              (("jid" . "2@lid") ("name" . "Bob")))))
      (whatsapp-root--render whatsapp--chats)
      (let ((before (buffer-substring-no-properties (point-min) (point-max))))
        (dotimes (i 200)
          (whatsapp-root--select-only (if (zerop (% i 2)) "1@lid" "2@lid")))
        (should (equal before (buffer-substring-no-properties (point-min) (point-max)))))
      (goto-char (whatsapp-root--chat-position "1@lid"))
      (should (equal (get-text-property (point) 'mouse-face) (whatsapp-profiles--hover-face))))))
(ert-deftest wa-rc13-long-toolbars-wrap-without-losing-button-identity ()
  (with-temp-buffer
    (dotimes (_ 12) (whatsapp--button "Useful action" #'ignore))
    (let ((pos (point-min)) (count 0))
      (while (< pos (point-max))
        (when (get-text-property pos 'whatsapp-command) (cl-incf count))
        (setq pos (next-single-property-change pos 'whatsapp-command nil (point-max))))
      (should (= count 12)))
    (goto-char (point-min))
    (while (not (eobp)) (should (<= (- (line-end-position) (line-beginning-position)) 72)) (forward-line 1))))

;; RC14: keep the original RC3 failing test untouched and strengthen the contract.
(ert-deftest wa-rc14-token-change-retains-draft-reply-and-undo ()
  (wa-rc2-chat
   (whatsapp-chat--render nil)
   (buffer-enable-undo)
   (insert "private fixture draft")
   (setq whatsapp-chat--reply '(:id "quoted-fixture" :participant "1@lid" :text "quoted"))
   (let ((before (buffer-string)) (position (point))
         (marker (marker-position whatsapp-chat--input-marker))
         (undo buffer-undo-list) (reply whatsapp-chat--reply)
         callback (calls 0))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _data cb) (cl-incf calls) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (ert-fail "A stale-account reply must not refresh"))))
       (whatsapp-chat-send-input)
       (let ((whatsapp-bridge-token "second-account-secret"))
         (funcall callback (wa-delivery-ack))
         (should (equal before (buffer-string)))
         (should (= position (point)))
         (should (= marker (marker-position whatsapp-chat--input-marker)))
         (should (eq undo buffer-undo-list))
         (should (eq reply whatsapp-chat--reply))
         (should-not whatsapp-chat--send-pending)
         (should (string-match-p "Draft retained" whatsapp--last-error))
         (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'unconfirmed))
         (should-not (plist-get (car whatsapp-chat--outgoing) :message-id))
         (should-not whatsapp-chat--outgoing-overlay)
         (should (= calls 1)))))))

(ert-deftest wa-rc14-url-change-reports-uncertain-without-secret-details ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "private original message")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (ert-fail "Wrong-origin refresh"))))
       (whatsapp-chat-send-input)
       (let ((whatsapp-bridge-url "https://second-origin.invalid"))
         (funcall callback '(502 ("error" . "sensitive provider reply")))
         (should (equal "private original message" (whatsapp-chat--current-input)))
         (should (stringp whatsapp--last-error))
         (dolist (s '("private original message" "fixture-token" "second-origin.invalid"
                      "sensitive provider reply" "fixture"))
           (should-not (string-match-p (regexp-quote s) whatsapp--last-error)))
         (should (string-match-p "delivery unconfirmed" whatsapp--last-error)))))))

(ert-deftest wa-rc14-stale-response-does-not-block-new-draft-edits ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "original")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb))))
       (whatsapp-chat-send-input))
     (insert " newer text")
     (let ((whatsapp-bridge-token "changed-account"))
       (funcall callback (wa-delivery-ack))
       (should (equal "original newer text" (whatsapp-chat--current-input)))
       (should-not whatsapp-chat--send-pending)
       (insert " still editable")
       (should (equal "original newer text still editable" (whatsapp-chat--current-input)))))))

(ert-deftest wa-rc14-duplicate-stale-response-is-not-reprocessed ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "fixture draft")
   (let (callback (calls 0))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (cl-incf calls) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (ert-fail "No late refresh"))))
       (whatsapp-chat-send-input)
       (let ((whatsapp-bridge-token "changed-account"))
         (funcall callback (wa-delivery-ack)))
       ;; Return to the old account: the same callback must not accept/clear now.
       (let ((error-before whatsapp--last-error))
         (funcall callback (wa-delivery-ack))
         (should (equal error-before whatsapp--last-error))
         (should (equal "fixture draft" (whatsapp-chat--current-input)))
         (should (= (length whatsapp-chat--outgoing) 1))
         (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'unconfirmed))
         (should-error (whatsapp-chat-send-input) :type 'user-error)
         (should (= calls 1)))))))

(ert-deftest wa-rc14-stale-callback-updates-owner-not-current-buffer ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "owner draft")
   (let ((owner (current-buffer)) callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb))))
       (whatsapp-chat-send-input))
     (with-temp-buffer
       (setq-local whatsapp--last-error "unrelated buffer state")
       (insert "unrelated buffer text")
       (let ((whatsapp-bridge-token "changed-account"))
         (funcall callback (wa-delivery-ack)))
       (should (equal "unrelated buffer state" whatsapp--last-error))
       (should (equal "unrelated buffer text" (buffer-string))))
     (with-current-buffer owner
       (should (equal "owner draft" (whatsapp-chat--current-input)))
       (should (string-match-p "Draft retained" whatsapp--last-error))))))

(ert-deftest wa-rc14-unchanged-account-acceptance-still-clears-unchanged-draft ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "original draft")
   (setq whatsapp--last-error "prior unrelated failure")
   (let (callback (refreshes 0))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (cl-incf refreshes))))
       (whatsapp-chat-send-input)
       (funcall callback (wa-delivery-ack))
       (should (equal "" (whatsapp-chat--current-input)))
       (should-not whatsapp--last-error)
       (should-not whatsapp-chat--send-pending)
       (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'accepted))
       (should (= refreshes 1))))))


(ert-deftest wa-rc15-accepted-refresh-error-does-not-escape-or-resend ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "sent fixture")
   (let (callback (posts 0) (refreshes 0))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_method _path _body cb) (cl-incf posts) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (cl-incf refreshes) (error "PRIVATE provider data"))))
       (whatsapp-chat-send-input)
       (funcall callback (wa-delivery-ack))
       (should (= posts 1)) (should (= refreshes 1))
       (should-not whatsapp-chat--send-pending)
       (should (equal "" (whatsapp-chat--current-input)))
       (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'accepted))
       (should (string-match-p "Do not resend" whatsapp--last-error))
       (should-not (string-match-p "PRIVATE" whatsapp--last-error))
       (funcall callback (wa-delivery-ack))
       (should (= posts 1)) (should (= refreshes 1))))))

(ert-deftest wa-rc15-accepted-refresh-error-retains-newer-draft ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "old draft")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh) (lambda (&rest _) (error "fixture"))))
       (whatsapp-chat-send-input)
       (goto-char (point-max)) (insert " edited while pending")
       (let ((before (whatsapp-chat--current-input)) (position (point))
             (marker (marker-position whatsapp-chat--input-marker)))
         (funcall callback (wa-delivery-ack))
         (should (equal before (whatsapp-chat--current-input)))
         (should (= position (point)))
         (should (= marker (marker-position whatsapp-chat--input-marker)))
         (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'accepted)))))))

(ert-deftest wa-rc15-stale-account-never-attempts-refresh ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "keep private draft")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (ert-fail "Refresh crossed an account boundary"))))
       (whatsapp-chat-send-input)
       (let ((whatsapp-bridge-token "other-account"))
         (funcall callback (wa-delivery-ack)))
       (should (equal "keep private draft" (whatsapp-chat--current-input)))
       (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'unconfirmed))
       (should (string-match-p "Account or conversation changed" whatsapp--last-error))))))

(ert-deftest wa-rc15-unconfirmed-send-never-attempts-refresh ()
  (wa-rc2-chat
   (whatsapp-chat--render nil) (insert "keep uncertain draft")
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_m _p _d cb) (setq callback cb)))
               ((symbol-function 'whatsapp-chat-refresh)
                (lambda (&rest _) (ert-fail "Unconfirmed send refreshed automatically"))))
       (whatsapp-chat-send-input)
       (funcall callback '(503 ("uncertain" . t)))
       (should (equal "keep uncertain draft" (whatsapp-chat--current-input)))
       (should (eq (plist-get (car whatsapp-chat--outgoing) :state) 'unconfirmed))))))

(provide 'recipient-ui-tests)
;;; recipient-ui-tests.el ends here
