;;; reliability-tests.el --- Cache and readiness regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)

(defmacro wa20-profile-fixture (&rest body)
  `(let* ((whatsapp-bridge-url "http://127.0.0.1:7337")
          (whatsapp-bridge-token "fixture-cache-token")
          (whatsapp-profiles--scope (whatsapp--origin-key))
          (whatsapp-profiles--meta (make-hash-table :test 'equal))
          (whatsapp-profiles--photos (make-hash-table :test 'equal))
          (whatsapp-profiles--photo-order nil)
          (whatsapp-profiles--buffers nil)
          (whatsapp-profiles--epoch "fixture-epoch")
          (whatsapp-profiles--generation 0)
          (whatsapp-profile-photos t)
          (whatsapp-profiles--consent-origin whatsapp-profiles--scope)
          (whatsapp-profiles--queue nil))
     (with-temp-buffer ,@body)))

(defun wa20-cache-fixture (kind expires)
  (let ((entry (list :image (list 'image :type 'png :synthetic kind)
                     :expires expires :bytes 100 :pixels 100)))
    (puthash (cons "123456789" kind) entry whatsapp-profiles--photos)
    (push (cons "123456789" kind) whatsapp-profiles--photo-order)
    entry))

(ert-deftest wa20-transient-photo-errors-preserve-fresh-avatar ()
  (wa20-profile-fixture
   (dolist (reason '("bridge-busy" "bridge-network" "cdn-network" "worker-timeout" "worker-failed"))
     (let ((entry (wa20-cache-fixture 'avatar (+ (float-time) 50))))
       (whatsapp-profiles--accept '(photo "123456789")
                                 `(("status") ("body" ("state" . "unavailable") ("reason" . ,reason))))
       (should (eq entry (gethash '("123456789" . avatar) whatsapp-profiles--photos)))))))

(ert-deftest wa20-transient-provider-failure-does-not-extend-expiry ()
  (wa20-profile-fixture
   (let* ((expiry (+ (float-time) 50)) (entry (wa20-cache-fixture 'avatar expiry)))
     (whatsapp-profiles--accept '(photo "123456789")
                               '(("status" . 200) ("body" ("state" . "unavailable")
                                 ("reason" . "provider-rejected") ("provider_http" . 503))))
     (should (eq entry (gethash '("123456789" . avatar) whatsapp-profiles--photos)))
     (should (= expiry (plist-get entry :expires))))))

(ert-deftest wa20-provider-denial-still-removes-photos ()
  (wa20-profile-fixture
   (dolist (status '(401 403 404 410))
     (wa20-cache-fixture 'avatar (+ (float-time) 50))
     (wa20-cache-fixture 'photo (+ (float-time) 50))
     (whatsapp-profiles--accept '(photo "123456789")
       `(("status" . 200) ("body" ("state" . "unavailable")
         ("reason" . "provider-rejected") ("provider_http" . ,status))))
     (should (= 0 (hash-table-count whatsapp-profiles--photos))))))

(ert-deftest wa20-generic-unavailability-is-not-a-transient-grant ()
  (wa20-profile-fixture
   (wa20-cache-fixture 'avatar (+ (float-time) 50))
   (whatsapp-profiles--accept '(avatar "123456789")
     '(("status" . 200) ("body" ("state" . "unavailable"))))
   (should (= 0 (hash-table-count whatsapp-profiles--photos)))))

(ert-deftest wa20-photo-variants-expire-independently ()
  (wa20-profile-fixture
   (dolist (expired '(avatar photo))
     (let* ((kept (if (eq expired 'avatar) 'photo 'avatar))
            (entry (wa20-cache-fixture kept (+ (float-time) 60))))
       (wa20-cache-fixture expired 1)
       (cl-letf (((symbol-function 'whatsapp-profiles--visible) (lambda () nil)))
         (whatsapp-profiles--tick))
       (should-not (gethash (cons "123456789" expired) whatsapp-profiles--photos))
       (should (eq entry (gethash (cons "123456789" kept) whatsapp-profiles--photos)))))))

(ert-deftest wa20-explicit-drop-still-invalidates-both-variants ()
  (wa20-profile-fixture
   (wa20-cache-fixture 'avatar (+ (float-time) 20))
   (wa20-cache-fixture 'photo (+ (float-time) 20))
   (whatsapp-profiles--drop-photo "123456789")
   (should (= 0 (hash-table-count whatsapp-profiles--photos)))
   (should-not whatsapp-profiles--photo-order)))

(ert-deftest wa20-removed-snapshot-still-invalidates-avatar ()
  (wa20-profile-fixture
   (wa20-cache-fixture 'avatar (+ (float-time) 20))
   (whatsapp-profiles--accept '(snapshot ("123456789"))
     '(("status" . 200) ("body" ("version" . 1) ("epoch" . "fixture-epoch")
       ("profiles" (("jid" . "123456789") ("photo_revision" . 2) ("photo_state" . "removed")
                    ("availability" . "unknown") ("activity" . "none")
                    ("availability_age" . 61) ("activity_age" . 9))))))
   (should (= 0 (hash-table-count whatsapp-profiles--photos)))))

(ert-deftest wa20-timeout-label-remains-bounded ()
  (wa20-profile-fixture
   (let* ((reply (whatsapp-profiles--worker-result 'exit 1
                   "{\"status\":null,\"body\":{\"state\":\"unavailable\",\"reason\":\"worker-timeout\",\"error\":\"PRIVATE_PROVIDER_TEXT\"}}"))
          (body (cdr (assoc "body" reply))))
     (should (equal (cdr (assoc "reason" body)) "worker-timeout"))
     (should-not (string-match-p "PRIVATE_PROVIDER_TEXT" (prin1-to-string reply))))))

(ert-deftest wa20-transient-failure-preserves-consent ()
  (wa20-profile-fixture
   (whatsapp-profiles--accept '(avatar "123456789")
      '(("status") ("body" ("state" . "unavailable") ("reason" . "worker-timeout"))))
   (should (equal whatsapp-profiles--consent-origin (whatsapp--origin-key)))))

(ert-deftest wa20-pending-session-observation-does-not-show-ready ()
  (let ((whatsapp-bridge-url "http://127.0.0.1:7337") (whatsapp-bridge-token "fixture-session-token")
        (whatsapp--session-snapshot nil))
    (whatsapp-session-observe '(("checked" . t) ("checking" . t) ("checked_age" . 0)
                               ("session_state" . "ready")) (whatsapp--origin-key))
    (should (string-match-p "unverified" (whatsapp-session-label)))))

(ert-deftest wa20-completed-ready-observation-still-shows-ready ()
  (let ((whatsapp-bridge-url "http://127.0.0.1:7337") (whatsapp-bridge-token "fixture-session-token")
        (whatsapp--session-snapshot nil))
    (whatsapp-session-observe '(("checked" . t) ("checking" . nil) ("checked_age" . 0)
                               ("session_state" . "ready")) (whatsapp--origin-key))
    (should (string-match-p "Backend connected" (whatsapp-session-label)))))

(ert-deftest wa20-pending-ready-cannot-trigger-profile-recovery ()
  (let ((whatsapp-bridge-url "http://127.0.0.1:7337") (whatsapp-bridge-token "fixture-session-token")
        (whatsapp--session-snapshot nil) recovered)
    (setq whatsapp--session-snapshot (list :origin (whatsapp--origin-key) :state "disconnected"))
    (cl-letf (((symbol-function 'whatsapp-profiles-session-recovered) (lambda () (setq recovered t))))
      (whatsapp-session-observe '(("checked" . t) ("checking" . t) ("checked_age" . 0)
                                 ("session_state" . "ready")) (whatsapp--origin-key))
      (should-not recovered))))

(ert-deftest wa20-pending-panel-does-not-instruct-test-media-yet ()
  (with-temp-buffer
    (special-mode)
    (setq-local whatsapp--transport-data '(("checked" . t) ("checking" . t) ("session_state" . "ready")))
    (whatsapp--transport-render)
    (should (string-match-p "previous observations" (buffer-string)))
    (should-not (string-match-p "Now verify events and test" (buffer-string)))))

(ert-deftest wa20-pending-then-completed-recovery-happens-once ()
  (let ((whatsapp-bridge-url "http://127.0.0.1:7337") (whatsapp-bridge-token "fixture-session-token")
        (whatsapp--session-snapshot nil) (recoveries 0))
    (cl-letf (((symbol-function 'whatsapp-profiles-session-recovered)
               (lambda () (cl-incf recoveries))))
      (whatsapp-session-observe '(("checked" . t) ("checking") ("checked_age" . 0)
                                 ("session_state" . "disconnected")) (whatsapp--origin-key))
      (whatsapp-session-observe '(("checked" . t) ("checking" . t) ("checked_age" . 0)
                                 ("session_state" . "ready")) (whatsapp--origin-key))
      (should (= recoveries 0))
      (should (string-match-p "unverified" (whatsapp-session-label)))
      (dotimes (_ 2)
        (whatsapp-session-observe '(("checked" . t) ("checking") ("checked_age" . 0)
                                   ("session_state" . "ready")) (whatsapp--origin-key)))
      (should (= recoveries 1)))))

(ert-deftest wa20-recovery-memory-does-not-cross-accounts ()
  (let ((whatsapp-bridge-url "http://127.0.0.1:7337") (whatsapp-bridge-token "fixture-account-one")
        (whatsapp--session-snapshot nil) recovered)
    (whatsapp-session-observe '(("checked" . t) ("checked_age" . 0)
                               ("session_state" . "disconnected")) (whatsapp--origin-key))
    (let ((whatsapp-bridge-token "fixture-account-two"))
      (cl-letf (((symbol-function 'whatsapp-profiles-session-recovered) (lambda () (setq recovered t))))
        (whatsapp-session-observe '(("checked" . t) ("checking" . t) ("checked_age" . 0)
                                   ("session_state" . "ready")) (whatsapp--origin-key))
        (whatsapp-session-observe '(("checked" . t) ("checking") ("checked_age" . 0)
                                   ("session_state" . "ready")) (whatsapp--origin-key))
        (should-not recovered)))))
