;;; tools-tests.el --- Conversation tools regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'whatsapp)

(defmacro whatsapp-tools-test-state (&rest body)
  `(let ((whatsapp-tools-state-directory (make-temp-file "wa-tools-" t))
         (whatsapp-tools--scope nil)
         (whatsapp-tools--preferences (make-hash-table :test 'equal))
         (whatsapp-tools--pending (make-hash-table :test 'equal))
         (whatsapp-bridge-url "http://127.0.0.1:7337")
         (whatsapp-bridge-token "fixture-account")
         (whatsapp--chats '((("jid" . "551111") ("name" . "Alice"))
                            (("jid" . "552222") ("name" . "Bob")))))
     (unwind-protect (progn ,@body)
       (delete-directory whatsapp-tools-state-directory t))))

(ert-deftest whatsapp-tools-archive-waits-for-provider-success ()
  (whatsapp-tools-test-state
   (let (callback request)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (method path payload cb)
                  (setq request (list method path payload) callback cb))))
       (whatsapp-archive-chat "551111" t)
       (should-not (whatsapp-tools--flag "551111" :archived))
       (should (equal request '("POST" "/archive" (("jid" . "551111") ("archive" . t)))))
       (should-error (whatsapp-archive-chat "551111" t) :type 'user-error)
       (funcall callback '(200 ("wuzapi_status" . 200) ("data" ("success" . t))))
       (should (whatsapp-tools--flag "551111" :archived))
       (setq whatsapp-tools--scope nil)
       (should (whatsapp-tools--flag "551111@s.whatsapp.net" :archived))
       (should (= #o600 (logand #o777 (file-modes (whatsapp-tools--state-file)))))
       (whatsapp-archive-chat "551111" nil)
       (should (eq (cdr (assoc "archive" (nth 2 request))) :json-false))
       (funcall callback '(200 ("wuzapi_status" . 200) ("data" ("success" . t))))
       (should-not (whatsapp-tools--flag "551111" :archived))))))

(ert-deftest whatsapp-tools-archive-refuses-ambiguous-results ()
  (whatsapp-tools-test-state
   (dolist (result '((200) (200 ("wuzapi_status" . 500) ("data" ("success" . t)))
                    (200 ("wuzapi_status" . 200) ("data" ("success" . nil)))
                    (nil ("error" . "deadline"))))
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_method _path _payload cb) (funcall cb result))))
       (whatsapp-archive-chat "551111" t)
       (should-not (whatsapp-tools--flag "551111" :archived))
       (should (= 0 (hash-table-count whatsapp-tools--pending)))))))

(ert-deftest whatsapp-tools-archive-late-account-result-is-ignored ()
  (whatsapp-tools-test-state
   (let (callback)
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (_method _path _payload cb) (setq callback cb))))
       (whatsapp-archive-chat "551111" t)
       (setq whatsapp-bridge-token "other-account")
       (funcall callback '(200 ("wuzapi_status" . 200) ("data" ("success" . t))))
       (should-not (whatsapp-tools--flag "551111" :archived))
       (setq whatsapp-bridge-token "fixture-account")
       (should-not (whatsapp-tools--flag "551111" :archived))))))

(ert-deftest whatsapp-tools-filters-and-pins-preserve-source-order ()
  (whatsapp-tools-test-state
   (whatsapp-pin-chat "552222")
   (should (equal (mapcar (lambda (chat) (cdr (assoc "jid" chat)))
                         (whatsapp-tools--ordered whatsapp--chats)) '("552222" "551111")))
   (should (equal (mapcar (lambda (chat) (cdr (assoc "jid" chat))) whatsapp--chats)
                  '("551111" "552222")))
   (whatsapp-tools--set-flag "551111" :archived t)
   (with-temp-buffer
     (whatsapp-root-mode)
     (setq whatsapp-root--filter 'all whatsapp-root--query "")
     (should-not (whatsapp-root--visible-p (car whatsapp--chats)))
     (setq whatsapp-root--filter 'archived)
     (should (whatsapp-root--visible-p (car whatsapp--chats)))
     (should-not (whatsapp-root--visible-p (cadr whatsapp--chats)))
     (setq whatsapp-root--filter 'pinned)
     (should (whatsapp-root--visible-p (cadr whatsapp--chats))))))

(ert-deftest whatsapp-tools-state-does-not-evaluate-input ()
  (whatsapp-tools-test-state
   (whatsapp-tools--ensure-state)
   (let ((file (whatsapp-tools--state-file)))
     (with-temp-file file (insert "#.(error \"must not evaluate\")"))
     (setq whatsapp-tools--scope nil)
     (should-not (whatsapp-tools--flag "551111" :archived))
     (should-error (whatsapp-pin-chat "invalid/../identity") :type 'user-error))))

(ert-deftest whatsapp-tools-state-refuses-symbolic-links ()
  (whatsapp-tools-test-state
   (let ((destination (make-temp-file "wa-unrelated-")))
     (unwind-protect
         (progn
           (whatsapp-tools--ensure-state)
           (make-symbolic-link destination (whatsapp-tools--state-file))
           (should-error (whatsapp-pin-chat "551111") :type 'user-error)
           (should-not (whatsapp-tools--flag "551111" :pinned))
           (should (= 0 (file-attribute-size (file-attributes destination)))))
       (delete-file destination)))))

(ert-deftest whatsapp-profile-photos-use-any-visible-graphical-frame ()
  (cl-letf (((symbol-function 'frame-list) (lambda () '(terminal graphical)))
            ((symbol-function 'frame-visible-p) (lambda (_frame) t))
            ((symbol-function 'display-graphic-p) (lambda (&optional frame) (eq frame 'graphical))))
    (should (whatsapp-profiles--graphical-p))))

(ert-deftest whatsapp-profile-photo-display-survives-selected-terminal ()
  (let ((image '(image :type png :data "fixture")))
    (cl-letf (((symbol-function 'frame-list) (lambda () '(terminal graphical)))
              ((symbol-function 'frame-visible-p) (lambda (_frame) t))
              ((symbol-function 'display-graphic-p) (lambda (&optional frame) (eq frame 'graphical)))
              ((symbol-function 'whatsapp-profiles--photo) (lambda (&rest _args) image)))
      (should (eq (whatsapp-profiles--display "551111") image)))))

(ert-deftest whatsapp-tools-avatar-retains-fallback-text-and-photo ()
  (let ((image '(image :type png :data "fixture")))
    (with-temp-buffer
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _frame) t))
                ((symbol-function 'whatsapp-profiles--photo) (lambda (&rest _args) image)))
        (whatsapp-profiles--insert-avatar "551111")
        (should (eq (get-text-property (point-min) 'display) image))
        (should (string-match-p "\\[" (buffer-string)))))))

(ert-deftest whatsapp-tools-archive-refreshes-visible-inbox ()
  (whatsapp-tools-test-state
   (let ((buffer (whatsapp--root-buffer)))
     (unwind-protect
         (with-current-buffer buffer
           (whatsapp-root--render whatsapp--chats)
           (should (whatsapp-root--chat-position "551111"))
           (cl-letf (((symbol-function 'whatsapp--request-async)
                      (lambda (_method _path _payload callback)
                        (funcall callback '(200 ("wuzapi_status" . 200) ("data" ("success" . t)))))))
             (whatsapp-archive-chat "551111" t))
           (should-not (whatsapp-root--chat-position "551111")))
       (kill-buffer buffer)))))

(ert-deftest whatsapp-tools-stale-chat-cannot-archive-another-account ()
  (whatsapp-tools-test-state
   (with-temp-buffer
     (whatsapp-chat-mode)
     (setq whatsapp-chat--jid "551111" whatsapp--read-origin (whatsapp--origin-key))
     (setq whatsapp-bridge-token "other-account")
     (should-error (whatsapp-toggle-chat-archive) :type 'user-error))))

(ert-deftest whatsapp-tools-stale-inbox-cannot-archive-another-account ()
  (whatsapp-tools-test-state
   (with-temp-buffer
     (whatsapp-root-mode)
     (whatsapp-root--render whatsapp--chats)
     (goto-char (whatsapp-root--chat-position "551111"))
     (setq whatsapp--read-origin (whatsapp--origin-key))
     (setq whatsapp-bridge-token "other-account")
     (cl-letf (((symbol-function 'whatsapp--request-async)
                (lambda (&rest _) (ert-fail "Stale inbox made an archive request"))))
       (should-error (whatsapp-toggle-chat-archive) :type 'user-error)))))

(ert-deftest whatsapp-tools-next-unread-skips-archived-conversations ()
  (whatsapp-tools-test-state
   (let ((whatsapp--chats '((("jid" . "551111") ("unread" . 1))
                            (("jid" . "552222") ("unread" . 1))))
         opened)
     (whatsapp-tools--set-flag "551111" :archived t)
     (cl-letf (((symbol-function 'whatsapp-open-chat) (lambda (jid) (setq opened jid))))
       (whatsapp-next-unread)
       (should (equal opened "552222"))))))

(ert-deftest whatsapp-profile-visible-graphical-window-schedules-avatar ()
  (let ((whatsapp-bridge-token "fixture-account")
        (whatsapp-profile-photos t)
        (whatsapp-profiles--capability 'ready)
        (whatsapp-profiles--queue nil)
        (whatsapp-profiles--photos (make-hash-table :test 'equal))
        (whatsapp-profiles--meta (make-hash-table :test 'equal))
        (whatsapp-profiles--pending (make-hash-table :test 'equal))
        (whatsapp-profiles--processes nil)
        (whatsapp-profiles--next-snapshot most-positive-fixnum)
        (whatsapp-profile-presence-enabled nil)
        started)
    (let ((whatsapp-profiles--scope (whatsapp--origin-key)))
      (puthash "551111" '(:photo-state "unknown") whatsapp-profiles--meta)
      (cl-letf (((symbol-function 'frame-list) (lambda () '(terminal graphical)))
                ((symbol-function 'frame-visible-p) (lambda (_frame) t))
                ((symbol-function 'display-graphic-p) (lambda (&optional frame) (eq frame 'graphical)))
                ((symbol-function 'whatsapp-profiles--visible) (lambda () '("551111")))
                ((symbol-function 'whatsapp-profiles--paint-status) #'ignore)
                ((symbol-function 'whatsapp-profiles--user-work-p) (lambda () nil))
                ((symbol-function 'whatsapp-profiles--start-child) (lambda (task) (push task started))))
        (whatsapp-profiles--tick)
        (should (equal started '((avatar "551111"))))))))
