;;; ui-smoke.el --- graphical fixture smoke check -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: AGPL-3.0-only
;; Usage: WHATSAPPEL_UI_OUTPUT=/absolute/directory xvfb-run -a emacs -Q -L . -l tests/ui-smoke.el
(require 'whatsapp)
(require 'cl-lib)
(setq debug-on-error t)
(let ((output (or (getenv "WHATSAPPEL_UI_OUTPUT") "/tmp/whatsappel-ui")))
  (make-directory output t)
  (load-theme 'modus-vivendi t)
  (set-frame-size (selected-frame) 120 42)
  (tool-bar-mode -1)
  (setq whatsapp-auto-load-images nil
        whatsapp--chats
        '((("jid" . "15550000001") ("name" . "Design studio") ("unread" . 3)
           ("last" . "The original photo is ready to review.") ("ts" . "1788972300"))
          (("jid" . "15550000002") ("name" . "Family") ("unread" . 1)
           ("last" . "See you this weekend!") ("ts" . "1788971200"))
          (("jid" . "120000000000@g.us") ("name" . "Open source team") ("unread" . 0)
           ("last" . "Tests passed. Ready for a review.") ("ts" . "1788968000"))))
  (switch-to-buffer (whatsapp--root-buffer))
  (whatsapp-root--render whatsapp--chats)
  (redisplay t)
  (sleep-for 0.5)
  (unless (display-graphic-p) (error "This smoke check requires graphical Emacs"))
  (let ((coding-system-for-write 'binary))
    (write-region (x-export-frames nil 'png) nil (expand-file-name "dashboard.png" output) nil 'silent))
  (switch-to-buffer (whatsapp--chat-buffer "15550000001"))
  (whatsapp-chat--render
   '((("id" . "fixture-1") ("from" . "15550000001@s.whatsapp.net")
       ("name" . "Design studio") ("text" . "Can you send the full-resolution photo?")
       ("ts" . "1788972100"))
     (("id" . "fixture-2") ("me" . t) ("from" . "me")
       ("text" . "Yes. I will use Original file to preserve the source bytes.") ("ts" . "1788972200"))
     (("id" . "fixture-3") ("from" . "15550000001@s.whatsapp.net") ("name" . "Design studio")
       ("kind" . "document") ("caption" . "design-notes.pdf") ("ts" . "1788972300"))))
  (goto-char (point-max))
  (insert "Here is the original. No resizing applied.")
  (let ((draft (whatsapp-chat--current-input)))
    (whatsapp-chat--render whatsapp-chat--messages)
    (unless (equal draft (whatsapp-chat--current-input)) (error "Draft lost on redraw")))
  (redisplay t)
  (sleep-for 0.5)
  (let ((coding-system-for-write 'binary))
    (write-region (x-export-frames nil 'png) nil (expand-file-name "conversation.png" output) nil 'silent))
  (with-temp-file (expand-file-name "ui-smoke.txt" output)
    (insert (format "PASS: graphical Emacs %s; dashboard and chat frame export; draft redraw retained.\n" emacs-version))
    (insert "Fixtures are fictional. No network, token, account linking or delivery was used.\n"))
  (kill-emacs 0))
